### ISSUE TITLE
Clarify Readme: Object Mapping

### ISSUE THREAD

**Issue by jedmao** [zzzaim/postcss-color-palette#5]
The README states that you can use an object mapping of CSS2 color keywords to color values, but is there any reason this has to be CSS2 color keywords? Can't it be anything as keys and anything as values?

**Comment by zaim** [comment]
All issues are on hold for now, as I am thinking of deprecating this plugin. Discussion at #9

**Comment by zzzaim** [comment]
To keep things simple, this plugin's scope will focus only on transforming CSS color keywords. Its meant for small, quick projects that does not want the overhead of large-ish CSS frameworks.

For replacing anything more than color keywords, I suggest just using CSS custom properties or SASS-like variables.

Thanks.
