### ISSUE TITLE
Use regex for props

### ISSUE THREAD

**Issue by jedmao** [zzzaim/postcss-color-palette#6]
How do you feel about using the following regex for a prop filter?

``` js
var COLOR_PROPS = /^(color|(background|border|outline)(-color)?|(text|box)-shadow)$/;
```

**Comment by zaim** [comment]
All issues are on hold for now, as I am thinking of deprecating this plugin. Discussion at #9

**Comment by zzzaim** [comment]
This is a good idea. I have pushed an implementation of this, and it will be available in next major release.

Thanks!
